### ISSUE TITLE
ActiveModel version 5.0.1 is not supported (yet)

### ISSUE THREAD

**Issue by preston** [softace/paperclip_database#25]
Rails v5.0.1 on Postgres 9.5.x:

    /Users/preston/.rvm/gems/ruby-2.3.3/gems/paperclip_database-2.3.1/lib/paperclip/storage/database.rb:196:in `block in flush_writes'
    /Users/preston/.rvm/gems/ruby-2.3.3/gems/paperclip_database-2.3.1/lib/paperclip/storage/database.rb:189:in `each'
    /Users/preston/.rvm/gems/ruby-2.3.3/gems/paperclip_database-2.3.1/lib/paperclip/storage/database.rb:189:in `flush_writes'
    /Users/preston/.rvm/gems/ruby-2.3.3/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:244:in `save'
    /Users/preston/.rvm/gems/ruby-2.3.3/gems/paperclip-5.1.0/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
    /Users/preston/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:396:in `instance_exec'
    ...

**Comment by SF5** [comment]
same thing ActiveModel version 5.0.2 is not supported (yet) rails 5.0.2

**Comment by preston** [comment]
Can anyone either confirm or deny that this project is maintained? Based on the commit history it looks like it may be abandoned. :-/

**Comment by Alanoudj** [comment]
Facing same issue for version 5.0.2, can anyone confirm if this issue is fixed or not?

**Comment by jarl-dk** [comment]
Fixed in version 3.0
